### ISSUE TITLE
help with understanding the output

### ISSUE THREAD

**Issue by C-young-maker** [gtonkinhill/panstripe#12]
Hi there, I am a novice, and I apologise if my question seems silly (as this might not be the place to post this). 

I am currently determining if there is any evidence for a temporal signal in the gene gain and loss pattern. (i.e. whether the pangenome is 'open' or 'closed'. A previous paper concluded that the pangenome was somewhat closed, hypothesising that homogenising forces acted against them (from a range of hypersaline environments). From the results I generated from the sample dataset I selected (with additionally sequenced genomes), im led to believe the pangenome is 'open' (from the Core and tip p values) compared to other papers that have referenced your fantastic tool. 

But im worried about this interpretation, especially when the branch lengths are very short. I've noticed that the distribution of my data doesn't follow a nice distribution. (especially looking at plot_residuals. 

I'm wondering if im on the right track or is something is wrong with my data? 

![final_6_figure_final ](https://github.com/gtonkinhill/panstripe/assets/95664286/b5338fe8-7ac4-43a8-9b53-1a273091ecdc)
![table ](https://github.com/gtonkinhill/panstripe/assets/95664286/a26cf42d-795a-49d3-9d73-e378ec7d6916)

fit model script: fit <- panstripe(pa, tree, asr_method = "max.parsimony", min_depth = NULL, family = "gaussian", intercept = FALSE, fit_method = 'glm', ci_type = 'perc', nboot = 1000, boot_type = 'branch', conf = 0.95, boot_pvalue = TRUE, quiet = FALSE)

**Comment by gtonkinhill** [comment]
Hi,

Given the number of ancestral gain and loss events as indicated in the bottom-right plot, it certainly seems like the dataset you are looking at has an 'open' pangenome. 

A 'closed' pangeome is a very poorly defined term and I generally prefer to refer to the 'rate of gene gain and loss' as this is less biased by the specific set of genomes included in a dataset and/or the timescale being considered. If you allow for a long enough time horizon, all pangenomes will be open.

If you are less sure about the confidence of your phylogeny at higher branches you can cut these out of the analysis using the `min_depth` parameter. You could also try using the "Tweedie" (`family="Tweedie"`) model along with this parameter.

Overall, based solely on the number of gain and loss events, it appears that your genome is relatively open.

**Comment by C-young-maker** [comment]
Hi there, 

Thank you so much for the clarification! I really appreciate it.
